name: BetterProtect
api: 5.3.0
main: Mrchlldev\BetterProtected\Loader
version: 1.0.0
author: Mrchlldev

commands:
  betterprotect:
    description: "Manage BetterProtected"
    permission: betterprotected.command
    aliases: ["bp", "bprotect"]

permissions:
  betterprotected.command:
    default: op
